In [1]:
import tensorflow as tf

In [2]:
tf.enable_eager_execution()

In [20]:
max_history = 5
category_size = 100

In [43]:
embeddings = tf.keras.layers.Embedding(output_dim=4, input_dim = category_size, 
                       input_length=max_history, mask_zero=True, name='embedding_category')

In [44]:
tt = [[1], [4]]
tt = tf.keras.preprocessing.sequence.pad_sequences(tt, max_history, padding='post')
tt

array([[1, 0, 0, 0, 0],
       [4, 0, 0, 0, 0]], dtype=int32)

In [45]:
tt=tf.convert_to_tensor(tt)

In [46]:
embeddings.compute_mask(tt)  ## compute masks

<tf.Tensor: id=156, shape=(2, 5), dtype=bool, numpy=
array([[ True, False, False, False, False],
       [ True, False, False, False, False]])>

In [47]:
input_embeddings=embeddings(tt)

In [48]:
input_embeddings

<tf.Tensor: id=171, shape=(2, 5, 4), dtype=float32, numpy=
array([[[-0.04444074, -0.0032139 ,  0.04822842,  0.04766295],
        [-0.01655685,  0.02014457,  0.01598669, -0.03960187],
        [-0.01655685,  0.02014457,  0.01598669, -0.03960187],
        [-0.01655685,  0.02014457,  0.01598669, -0.03960187],
        [-0.01655685,  0.02014457,  0.01598669, -0.03960187]],

       [[ 0.02881174, -0.02919713,  0.0369429 ,  0.03400585],
        [-0.01655685,  0.02014457,  0.01598669, -0.03960187],
        [-0.01655685,  0.02014457,  0.01598669, -0.03960187],
        [-0.01655685,  0.02014457,  0.01598669, -0.03960187],
        [-0.01655685,  0.02014457,  0.01598669, -0.03960187]]],
      dtype=float32)>

In [49]:
tf.keras.layers.GlobalAveragePooling1D(name='_avg_embedding')(input_embeddings, mask=embeddings.compute_mask(tt))

<tf.Tensor: id=183, shape=(2, 4), dtype=float32, numpy=
array([[-0.04444074, -0.0032139 ,  0.04822842,  0.04766295],
       [ 0.02881174, -0.02919713,  0.0369429 ,  0.03400585]],
      dtype=float32)>